inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: '2.6'

Naming/InclusiveLanguage:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - ext/semian/extconf.rb
