version: "3.7"
services:
  semian: &base
    container_name: semian
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
      target: base
      args:
        RUBY_VERSION: 3.1.2
    working_dir: /workspace
    volumes:
      # This is where VS Code should expect to find your project's source code
      # and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspace
      - ../.vscode-server:/root/.vscode-server
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
    # Required for ptrace-based debuggers like C++, Go, and Rust
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    depends_on:
      - redis
      - mysql
      - toxiproxy
    command:
      - /bin/bash
      - -c
      - |
        bundle install
        sleep infinity

  test:
    <<: *base
    hostname: semian
    container_name: semian-tests
    build:
      context: ../
      dockerfile: dockerfiles/semian-ci
      args:
        RUBY_VERSION: 3.1.2
    command:
      - bash
      - -c
      - |-
        bundle config set --local path 'vendor/bundle'
        ./scripts/run_tests.sh
    profiles:
      - test
    restart: never

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.4.0
    container_name: toxiproxy
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
